server:
  port: 8181

fake-api:
  url: https://fakestoreapi.com

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password:
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  cloud:
    loadbalancer:
      ribbon:
        enable: true



